"""
对比10.0_STA_DCD_CHECK.py生成的YAML和CodeGen的report
"""
import yaml
from pathlib import Path

def compare_yaml_report():
    """Compare YAML generated by tool vs CodeGen report."""
    
    # Paths
    yaml_path = Path("Check_modules/10.0_STA_DCD_CHECK/outputs/10.0_STA_DCD_CHECK.yaml")
    report_path = Path("Check_modules/10.0_STA_DCD_CHECK/reports/IMP-10-0-0-00.rpt")
    
    # Load YAML
    with open(yaml_path, 'r', encoding='utf-8') as f:
        yaml_data = yaml.safe_load(f)
    
    # Load Report
    with open(report_path, 'r', encoding='utf-8') as f:
        report_lines = f.readlines()
    
    print("="*80)
    print("YAML vs Report Comparison for IMP-10-0-0-00")
    print("="*80)
    
    # Extract item data from YAML
    item_data = yaml_data['check_items']['IMP-10-0-0-00']
    
    # Parse report first line
    report_first_line = report_lines[0].strip()
    status_from_report = "pass" if report_first_line.startswith("PASS:") else "fail"
    
    print(f"\n1. Status Comparison:")
    print(f"   YAML status: {item_data['status']}")
    print(f"   Report status: {status_from_report}")
    if item_data['status'] == status_from_report:
        print("   ✅ Status matches!")
    else:
        print("   ❌ Status mismatch!")
    
    print(f"\n2. Description:")
    print(f"   YAML: {item_data['description']}")
    
    print(f"\n3. Details Count:")
    yaml_infos = item_data.get('infos', [])
    yaml_warnings = item_data.get('warnings', [])
    yaml_failures = item_data.get('failures', [])
    total_yaml_details = len(yaml_infos) + len(yaml_warnings) + len(yaml_failures)
    
    # Count report details
    report_detail_count = 0
    for line in report_lines:
        if line.strip().startswith(tuple(str(i) + ":" for i in range(1, 100))):
            report_detail_count += 1
    
    print(f"   YAML: {total_yaml_details} (infos: {len(yaml_infos)}, warnings: {len(yaml_warnings)}, failures: {len(yaml_failures)})")
    print(f"   Report: {report_detail_count}")
    if total_yaml_details == report_detail_count:
        print("   ✅ Detail count matches!")
    else:
        print("   ⚠️ Detail count differs!")
    
    print(f"\n4. Detail Comparison:")
    print(f"\n{'='*80}")
    print("YAML Details:")
    print(f"{'='*80}")
    for idx, info in enumerate(yaml_infos, 1):
        print(f"\n[{idx}] {info['detail']}")
        print(f"    Reason: {info['reason']}")
        print(f"    Source: {info['source_file']}:{info['source_line']}")
    
    print(f"\n{'='*80}")
    print("Report Details:")
    print(f"{'='*80}")
    in_details = False
    for line in report_lines[1:]:  # Skip first line (status)
        line = line.strip()
        if line and not line.startswith("Info Occurrence:"):
            if line[0].isdigit() and ":" in line:
                print(f"\n{line}")
            elif in_details:
                print(f"    {line}")
        if line.startswith("Info Occurrence:") or (line and line[0].isdigit()):
            in_details = True
    
    print(f"\n{'='*80}")
    print("Key Differences Analysis:")
    print(f"{'='*80}")
    
    # Compare detail texts
    differences = []
    
    for idx, info in enumerate(yaml_infos):
        yaml_detail = info['detail']
        yaml_reason = info['reason']
        
        # Find corresponding report line
        report_detail = None
        for line in report_lines:
            if f"{idx+1}: Info:" in line:
                report_detail = line.strip()
                break
        
        if report_detail:
            # Extract just the detail name from report
            report_name = report_detail.split(': Info: ')[1].split('.')[0] if '. In line' in report_detail else report_detail.split(': Info: ')[1].split(':')[0]
            
            if yaml_detail != report_name:
                differences.append({
                    'index': idx + 1,
                    'yaml': yaml_detail,
                    'report': report_name,
                    'yaml_reason': yaml_reason
                })
    
    if differences:
        print(f"\nFound {len(differences)} differences in detail text:\n")
        for diff in differences:
            print(f"Detail #{diff['index']}:")
            print(f"  YAML   : {diff['yaml']}")
            print(f"  Report : {diff['report']}")
            print(f"  YAML Reason: {diff['yaml_reason']}")
            print()
    else:
        print("\n✅ All detail texts match exactly!")
    
    print(f"\n{'='*80}")
    print("Reason Text Comparison:")
    print(f"{'='*80}")
    
    yaml_reasons = [info['reason'] for info in yaml_infos]
    
    # Extract reasons from report
    report_reasons = []
    for line in report_lines:
        if ': Info:' in line and '[' in line:
            # Extract reason from line like "1: Info: XXX: YYY[TAG]"
            if ': ' in line.split(': Info: ')[1]:
                reason_part = line.split(': Info: ')[1].split(': ', 1)
                if len(reason_part) > 1:
                    report_reasons.append(reason_part[1].split('.')[0])
    
    print(f"\nYAML Reasons:")
    for idx, reason in enumerate(yaml_reasons, 1):
        print(f"  {idx}. {reason}")
    
    print(f"\nReport Reasons (extracted):")
    for idx, reason in enumerate(report_reasons, 1):
        print(f"  {idx}. {reason}")
    
    print(f"\n{'='*80}")
    print("CONCLUSION")
    print(f"{'='*80}")
    
    if item_data['status'] == status_from_report and total_yaml_details == report_detail_count:
        print("✅ Overall structure matches!")
        print("✅ CodeGen produces correct YAML-compatible output!")
        if differences:
            print(f"⚠️ Minor differences in {len(differences)} detail text(s)")
            print("   (This may be due to different reason formatting)")
    else:
        print("❌ Structural differences detected")
        print("   Need to investigate format inconsistencies")


if __name__ == '__main__':
    compare_yaml_report()
