JEDAI_MODELS = {
    "azure-gpt-4o": {"family": "AzureOpenAI", "deployment": "gpt-4o", "endpoint": "https://llmtest01-eastus2.openai.azure.com"},
    "azure-gpt-5": {"family": "AzureOpenAI", "deployment": "gpt-5", "endpoint": "https://llmtest01-eastus2.openai.azure.com"},
    "azure-gpt-5-2": {"family": "AzureOpenAI", "deployment": "gpt-5-2", "endpoint": "https://llmtest01-eastus2.openai.azure.com"},
    "azure-gpt-5-mini": {"family": "AzureOpenAI", "deployment": "gpt-5-mini", "endpoint": "https://llmtest01-eastus2.openai.azure.com"},
    "azure-o4-mini": {"family": "AzureOpenAI", "deployment": "o4-mini", "endpoint": "https://llmtest01-eastus2.openai.azure.com"},
    "azure-rnd01-gpt4-vision": {"family": "AzureOpenAI", "deployment": "rnd01-gpt4-vision", "endpoint": "https://llmtest01-westus.openai.azure.com"},
    "claude-3-5-haiku": {"family": "Claude", "deployment": "claude-3-5-haiku", "location": "us-east5"},
    "claude-3-5-sonnet-v2": {"family": "Claude", "deployment": "claude-3-5-sonnet-v2", "location": "us-east5"},
    "claude-3-7-sonnet": {"family": "Claude", "deployment": "claude-3-7-sonnet", "location": "us-east5"},
    "claude-haiku-4-5": {"family": "Claude", "deployment": "claude-haiku-4-5", "location": "us-east5"},
    "claude-opus-4": {"family": "Claude", "deployment": "claude-opus-4", "location": "us-east5"},
    "claude-opus-4-1": {"family": "Claude", "deployment": "claude-opus-4-1", "location": "us-east5"},
    "claude-sonnet-4": {"family": "Claude", "deployment": "claude-sonnet-4", "location": "us-east5"},
    "claude-sonnet-4-5": {"family": "Claude", "deployment": "claude-sonnet-4-5", "location": "us-east5"},
    "deepseek-r1-0528-maas": {"family": "DeepSeek", "deployment": "deepseek-ai/deepseek-r1-0528-maas", "location": "us-central1"},
    "deepseek-v3-1-maas": {"family": "DeepSeek", "deployment": "deepseek-ai/deepseek-v3.1-maas", "location": "us-west2"},
    "gemini-2-5-flash": {"family": "GEMINI", "deployment": "gemini-2.5-flash", "location": "us-central1"},
    "gemini-2-5-flash-lite": {"family": "GEMINI", "deployment": "gemini-2.5-flash-lite", "location": "us-central1"},
    "gemini-2-5-pro": {"family": "GEMINI", "deployment": "gemini-2.5-pro", "location": "us-central1"},
    "gemini-3-pro-preview": {"family": "GEMINI", "deployment": "gemini-3-pro-preview", "location": "global"},
    "llama-3-1-405b-instruct-maas": {"family": "Meta-Llama", "deployment": "meta/llama-3.1-405b-instruct-maas", "location": "us-central1"},
    "llama-3-1-70b-instruct-maas": {"family": "Meta-Llama", "deployment": "meta/llama-3.1-70b-instruct-maas", "location": "us-central1"},
    "llama-3-1-8b-instruct-maas": {"family": "Meta-Llama", "deployment": "meta/llama-3.1-8b-instruct-maas", "location": "us-central1"},
    "llama-3-3-70b-instruct-maas": {"family": "Meta-Llama", "deployment": "meta/llama-3.3-70b-instruct-maas", "location": "us-central1"},
    "llama-4-maverick-17b-128e-instruct-maas": {"family": "Meta-Llama", "deployment": "meta/llama-4-maverick-17b-128e-instruct-maas", "location": "us-east5"},
    "llama-4-scout-17b-16e-instruct-maas": {"family": "Meta-Llama", "deployment": "meta/llama-4-scout-17b-16e-instruct-maas", "location": "us-east5"},
    "onprem-gemma-3-4b-it": {"family": "OnPremise", "deployment": "gemma_3_4b_it"},
    "onprem-gpt-oss-120b": {"family": "OnPremise", "deployment": "openai/gpt-oss-120b"},
    "onprem-gpt-oss-20b": {"family": "OnPremise", "deployment": "openai/gpt-oss-20b"},
    "onprem-llama3-1-jedai-model-chat-2": {"family": "OnPremise", "deployment": "Llama3.1_JEDAI_MODEL_CHAT_2"},
    "onprem-llama3-3-jedai-model-chat-2": {"family": "OnPremise", "deployment": "Llama3.3_JEDAI_MODEL_CHAT_2"},
    "onprem-nvidia-llama-3-3-nemotron-super-49b-v1-5": {"family": "OnPremise", "deployment": "nvidia/llama-3_3-nemotron-super-49b-v1_5"},
    "onprem-nvidia-nvidia-nemotron-3-nano-30b-a3b-bf16": {"family": "OnPremise", "deployment": "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16"},
    "onprem-qwen3-32b": {"family": "OnPremise", "deployment": "Qwen3-32B"},
    "openai": {"family": "OpenAI", "deployment": "OpenAI"},
    "qwen3-235b-a22b-instruct-2507-maas": {"family": "Qwen", "deployment": "qwen/qwen3-235b-a22b-instruct-2507-maas", "location": "us-south1"},
    "qwen3-coder-480b-a35b-instruct-maas": {"family": "Qwen", "deployment": "qwen/qwen3-coder-480b-a35b-instruct-maas", "location": "us-south1"},
}

MODEL_ALIASES = {
    "gemini-2.5": "gemini-2-5-pro",
    "gemini": "gemini-2-5-pro",
    "claude-3.7": "claude-3-7-sonnet",
    "claude": "claude-sonnet-4-5",
    "sonnet-3.5": "claude-3-5-sonnet-v2",
    "claude-3.5": "claude-3-5-sonnet-v2",
    "claude-sonnet-4.5": "claude-sonnet-4-5",
    "sonnet-4": "claude-sonnet-4-5",
    "sonnet-4.5": "claude-sonnet-4-5",
    "deepseek-r1": "deepseek-r1-0528-maas",
    "deepseek": "deepseek-r1-0528-maas",
    "llama-3.3": "llama-3-3-70b-instruct-maas",
    "llama": "llama-3-3-70b-instruct-maas",
    "gpt-4o": "azure-gpt-4o",
    "gpt-4": "azure-gpt-4o",
}

def get_model_config(model_name: str):
    # Check aliases first
    real_name = MODEL_ALIASES.get(model_name, model_name)
    return JEDAI_MODELS.get(real_name), real_name