# Generated by Developer Agent
# Item ID: IMP-10-0-0-00
# Model: claude-sonnet-4-5
# Generated at: 2026-01-28T14:06:36.477378

def check_existence(items):
    """
    Universal existence checker.
    
    Args:
        items: List of dictionaries representing found items
    
    Returns:
        Dict with keys: is_match (bool), reason (str), evidence (list)
    """
    if not isinstance(items, list):
        items = []
    
    is_match = len(items) > 0
    
    return {
        'is_match': is_match,
        'reason': f"Found {len(items)} item(s)" if is_match else "No items found",
        'evidence': items
    }