# -*- coding: utf-8 -*-
"""
NetlistSpefVersionChecker.py - Checker Implementation for IMP-10-0-0-00

Description:
    Confirm the netlist/spef version is correct.

Author: CodeGen Agent
Created: 2026-01-02
Version: v1.0.0

This file was auto-generated by CodeGen Agent.
Manual modifications may be overwritten on regeneration.
"""


from pathlib import Path
import gzip
import re
import sys
from typing import List, Dict, Tuple, Optional, Any


# Add common module to path
_SCRIPT_DIR = Path(__file__).resolve().parent
_CHECK_MODULES_DIR = _SCRIPT_DIR.parents[2]  # Go up to Check_modules/
_COMMON_DIR = _CHECK_MODULES_DIR / 'common'
if str(_COMMON_DIR) not in sys.path:
    sys.path.insert(0, str(_COMMON_DIR))

# Framework imports
from base_checker import BaseChecker, CheckResult, ConfigurationError
from output_formatter import DetailItem, Severity, create_check_result
from checker_templates.waiver_handler_template import WaiverHandlerMixin
from checker_templates.output_builder_template import OutputBuilderMixin

from checker_templates.input_file_parser_template import InputFileParserMixin


# MANDATORY: Inherit mixins in correct order (InputFileParserMixin first if used)
class NetlistSpefVersionChecker(InputFileParserMixin, OutputBuilderMixin, WaiverHandlerMixin, BaseChecker):
    """
    IMP-10-0-0-00: Confirm the netlist/spef version is correct.
    
    Checking Types:
    - Type 1: requirements=N/A, pattern_items [], waivers=N/A/0 → Boolean Check
    - Type 2: requirements>0, pattern_items [...], waivers=N/A/0 → Value Check
    - Type 3: requirements>0, pattern_items [...], waivers>0 → Value Check with Waiver Logic
    - Type 4: requirements=N/A, pattern_items [], waivers>0 → Boolean Check with Waiver Logic
    
    Template Library v1.1.0:
    - Uses InputFileParserMixin for parsing (parse_log_with_patterns, normalize_command)
    - Uses WaiverHandlerMixin for waiver processing (parse_waive_items, match_waiver_entry)
    - Uses OutputBuilderMixin for result construction (build_complete_output)
    """
    
    # =========================================================================
    # UNIFIED DESCRIPTIONS - Class-level constants (LLM-Generated)
    # =========================================================================
    FOUND_DESC = "Netlist/SPEF file read successfully"
    MISSING_DESC = "Netlist/SPEF file read failed or not found"
    EXTRA_DESC = "Additional issues found"
    FOUND_REASON = "File read successfully with correct version"
    MISSING_REASON = "File read failed or version not found"
    
    def __init__(self):
        """Initialize the checker."""
        super().__init__(
            check_module="IMP",
            item_id="IMP-10-0-0-00",
            item_desc="Confirm the netlist/spef version is correct."
        )
        # MANDATORY: Metadata tracking for debug (Golden pattern)
        # Used by helper methods to track line numbers for DetailItem
        self._metadata: Dict[str, Dict[str, Any]] = {}
        # Store parsed data
        self._parsed_items: List[Dict] = []
    
    # =========================================================================
    # Main Check Execution (Template - Fixed, v2.1 Golden-Aligned)
    # =========================================================================
    
    def execute_check(self) -> CheckResult:
        """
        Execute check with automatic type detection and delegation.
        
        v2.1: Aligned with Golden design pattern:
        1. Parse input files first via _parse_input_files()
        2. Pass parsed data to _execute_typeN(parsed_data)
        
        Returns:
            CheckResult based on detected checker type
        """
        try:
            if self.root is None:
                raise RuntimeError("Checker not initialized. Call init_checker() first.")
            
            # Parse input files first (Golden pattern)
            parsed_data = self._parse_input_files()
            
            # Detect checker type (use BaseChecker method)
            checker_type = self.detect_checker_type()
            
            # Execute based on type, passing parsed data
            if checker_type == 1:
                return self._execute_type1(parsed_data)
            elif checker_type == 2:
                return self._execute_type2(parsed_data)
            elif checker_type == 3:
                return self._execute_type3(parsed_data)
            else:  # checker_type == 4
                return self._execute_type4(parsed_data)
        except ConfigurationError as e:
            return e.check_result
    
    # =========================================================================
    # Input Parsing (LLM-Generated)
    # =========================================================================
    
    def _parse_input_files(self) -> Dict[str, Any]:
        """
        Parse input files to extract netlist and SPEF version information.
        
        Returns:
            Dict with keys:
            - netlist_info: Dict with netlist metadata
            - spef_info: Dict with SPEF metadata
            - errors: List of error messages
        """
        # Initialize metadata storage
        self._metadata = {}
        
        # Parse STA log first
        sta_log_info = self._parse_sta_log()
        
        netlist_info = {}
        spef_info = {}
        errors = list(sta_log_info.get('errors', []))
        
        # Parse netlist file if found
        if sta_log_info.get('netlist_path'):
            netlist_path = sta_log_info['netlist_path']
            netlist_info = self._parse_netlist_version(netlist_path)
            netlist_info['path'] = str(netlist_path)
            netlist_info['status'] = sta_log_info.get('netlist_status', 'Unknown')
            
            if not netlist_info.get('version'):
                errors.append(f"Failed to extract version from netlist: {netlist_path.name}")
        elif sta_log_info.get('netlist_relative_path'):
            # Netlist path found but file doesn't exist
            netlist_info['relative_path'] = sta_log_info['netlist_relative_path']
            netlist_info['status'] = sta_log_info.get('netlist_status', 'Unknown')
            netlist_info['note'] = 'File path found in log but actual file not accessible'
        else:
            errors.append("Netlist file path not found in STA log")
        
        # Parse SPEF file if found
        if sta_log_info.get('spef_path'):
            spef_path = sta_log_info['spef_path']
            spef_info = self._parse_spef_version(spef_path)
            spef_info['path'] = str(spef_path)
            spef_info['status'] = sta_log_info.get('spef_status', 'Unknown')
            
            if not spef_info.get('version'):
                errors.append(f"Failed to extract version from SPEF: {spef_path.name}")
        else:
            # SPEF might be intentionally skipped or not found
            spef_status = sta_log_info.get('spef_status', 'Not Found')
            spef_info['status'] = spef_status
            if spef_status == 'Skipped':
                # Get skip reason from metadata
                metadata = self._metadata.get('spef_skipped', {})
                skip_reason = spef_info.get('skip_reason', 'SPEF reading was skipped')
                skip_reason = skip_reason.replace('[INFO] ', '').replace('INFO: ', '')
                spef_info['skip_reason'] = skip_reason
            elif spef_status == 'Not Found':
                if 'spef_step_end' not in self._metadata:
                    errors.append("SPEF file path not found in STA log")
        
        return {
            'netlist_info': netlist_info,
            'spef_info': spef_info,
            'errors': errors
        }
    
    # =========================================================================
    # Type 1: Boolean Check (LLM-Generated)
    # =========================================================================
    
    def _execute_type1(self, parsed_data: Dict[str, Any]) -> CheckResult:
        """
        Type 1: Boolean check - verify netlist and SPEF are loaded successfully
        
        架构：Boolean Logic + 无Waiver
        Pass Condition: Both files read with Status: Success
        Fail Condition: Any file read failed
        """
        def parse_data():
            """调用共享的Boolean Check Logic"""
            return self._boolean_check_logic(parsed_data)
        
        return self.execute_boolean_check(
            parse_data_func=parse_data,
            has_waiver=False,
            found_desc=self.FOUND_DESC,
            missing_desc=self.MISSING_DESC,
            extra_desc=self.EXTRA_DESC,
            name_extractor=self._build_name_extractor()
        )
    
    # =========================================================================
    # Type 2: Value Check (LLM-Generated)
    # =========================================================================
    
    def _execute_type2(self, parsed_data: Dict[str, Any]) -> CheckResult:
        """
        Type 2: Value check - match version info from pattern_items
        
        架构：Pattern Logic + 无Waiver
        Pass Condition: Pattern items found in output
        Fail Condition: Pattern items not found
        """
        def parse_data():
            """调用共享的Pattern Check Logic"""
            return self._pattern_check_logic(parsed_data)
        
        return self.execute_value_check(
            parse_data_func=parse_data,
            has_waiver=False,
            found_desc="Netlist/SPEF version is correct",
            missing_desc="Netlist/SPEF version isn't correct",
            extra_desc=self.EXTRA_DESC,
            name_extractor=self._build_name_extractor()
        )
    
    # =========================================================================
    # Type 3: Value Check with Waiver Logic (LLM-Generated)
    # =========================================================================
    
    def _execute_type3(self, parsed_data: Dict[str, Any]) -> CheckResult:
        """
        Type 3: Value check with waiver - 复用 Type2 逻辑
        
        架构：Pattern Logic + Waiver
        Pass Condition: Pattern items found or waiver valid
        Fail Condition: Pattern items not found and waiver invalid
        """
        def parse_data():
            """调用共享的Pattern Check Logic (与Type2相同)"""
            return self._pattern_check_logic(parsed_data)
        
        return self.execute_value_check(
            parse_data_func=parse_data,
            has_waiver=True,  # Type3特有: 启用waiver处理
            found_desc="Netlist/SPEF version is correct",
            missing_desc="Netlist/SPEF version isn't correct",
            extra_desc=self.EXTRA_DESC,
            extra_severity=Severity.FAIL,
            name_extractor=self._build_name_extractor()
        )
    
    # =========================================================================
    # Type 4: Boolean Check with Waiver Logic (LLM-Generated)
    # =========================================================================
    
    def _execute_type4(self, parsed_data: Dict[str, Any]) -> CheckResult:
        """
        Type 4: Boolean check with waiver - 复用 Type1 逻辑
        
        架构：Boolean Logic + Waiver
        Pass Condition: Check passed or waiver valid
        Fail Condition: Check failed and waiver invalid/expired
        """
        def parse_data():
            """调用共享的Boolean Check Logic (与Type1相同)"""
            return self._boolean_check_logic(parsed_data)
        
        return self.execute_boolean_check(
            parse_data_func=parse_data,
            has_waiver=True,  # Type4特有: 启用waiver处理
            found_desc=self.FOUND_DESC,
            missing_desc=self.MISSING_DESC,
            extra_desc=self.EXTRA_DESC,
            name_extractor=self._build_name_extractor()
        )

    # =========================================================================
    # Helper Methods (LLM-Generated)
    # =========================================================================
    
    def _build_name_extractor(self):
        """返回 name_extractor 函数，用于格式化输出"""
        def extract_name(name: str, metadata: Any) -> str:
            if isinstance(metadata, dict):
                version = metadata.get('version', '')
                date = metadata.get('date', '')
                path = metadata.get('path', '')
                
                parts = [name]
                if path:
                    parts.append(f"Path: {Path(path).name}")
                if version:
                    parts.append(f"Version: {version}")
                if date:
                    parts.append(f"Date: {date}")
                
                return ", ".join(parts)
            return name
        return extract_name

    # =========================================================================
    # Helper: Extract Data (辅助函数，所有Type共用)
    # =========================================================================

    def _extract_data(self, parsed_data: Dict[str, Any]) -> tuple:
        """Extract common data from parsed_data for all Types"""
        return (
            parsed_data.get('netlist_info', {}),
            parsed_data.get('spef_info', {}),
            parsed_data.get('errors', [])
        )

    # =========================================================================
    # Logic Check Modules (Layer 2: 核心逻辑模块)
    # =========================================================================

    def _boolean_check_logic(self, parsed_data: Dict[str, Any]) -> tuple:
        """
        Boolean Check Logic (Type1/4共享)
        
        核心业务逻辑：检查文件是否存在 (存在性判断)
        
        Returns:
            tuple: (found_items, missing_items, extra_items)
        """
        netlist_info, spef_info, errors = self._extract_data(parsed_data)
        
        found_items = {}
        missing_items = {}
        extra_items = {}
        
        # Check netlist
        netlist_status = netlist_info.get('status', 'Not Found')
        if netlist_status == 'Success':
            if netlist_info.get('path'):
                netlist_path = netlist_info.get('path', 'Unknown')
                version_str = netlist_info.get('version', 'Unknown')
                date_str = netlist_info.get('full_timestamp', netlist_info.get('date', 'Unknown'))
                
                metadata = self._metadata.get('netlist_success', {})
                item_name = f"Netlist File"
                found_items[item_name] = {
                    'line_number': metadata.get('line_number', 0),
                    'file_path': metadata.get('file_path', ''),
                    'version': version_str,
                    'date': date_str,
                    'path': netlist_path
                }
            elif netlist_info.get('relative_path'):
                netlist_rel_path = netlist_info['relative_path']
                metadata = self._metadata.get('netlist_success', {})
                item_name = f"Netlist File"
                found_items[item_name] = {
                    'line_number': metadata.get('line_number', 0),
                    'file_path': metadata.get('file_path', ''),
                    'note': 'found in log, file not accessible',
                    'path': netlist_rel_path
                }
        else:
            missing_items[f"Netlist File"] = {
                'reason': f"Status: {netlist_status}"
            }
        
        # Check SPEF
        spef_status = spef_info.get('status', 'Not Found')
        if spef_status == 'Success':
            if spef_info.get('path'):
                spef_path = spef_info.get('path', 'Unknown')
                version_str = spef_info.get('version', 'Unknown')
                date_str = spef_info.get('date', 'Unknown')
                
                metadata = self._metadata.get('spef_step_end', {})
                item_name = f"SPEF File"
                found_items[item_name] = {
                    'line_number': metadata.get('line_number', 0),
                    'file_path': metadata.get('file_path', ''),
                    'version': version_str,
                    'date': date_str,
                    'path': spef_path
                }
        elif spef_status == 'Skipped':
            metadata = self._metadata.get('spef_skipped', {})
            skip_reason = spef_info.get('skip_reason', 'SPEF reading was skipped')
            missing_items["SPEF Reading was skipped"] = {
                'line_number': 0,
                'file_path': 'N/A',
                'reason': skip_reason
            }
        else:
            missing_items[f"SPEF File"] = {
                'reason': f"Status: {spef_status}"
            }
        
        # Add other errors as extra items
        for error in errors:
            if not any(e in error for e in ["SPEF reading was skipped"]):
                extra_items[f"Error: {error}"] = {
                    'reason': 'Unexpected error'
                }
        
        return found_items, missing_items, extra_items


    def _pattern_check_logic(self, parsed_data: Dict[str, Any]) -> tuple:
        """
        Pattern Check Logic (Type2/3共享)
        
        核心业务逻辑：匹配版本信息pattern (正则匹配)
        
        Returns:
            tuple: (found_items, missing_items, extra_items)
        """
        netlist_info, spef_info, errors = self._extract_data(parsed_data)
        
        # Get pattern_items from requirements
        requirements = self.item_data.get('requirements', {})
        pattern_items = requirements.get('pattern_items', [])
        
        found_items = {}
        missing_items = {}
        extra_items = {}
        
        # Collect all content to search
        all_content = []
        
        # Add netlist version info
        if netlist_info.get('tool'):
            all_content.append(f"Tool: {netlist_info['tool']}")
        if netlist_info.get('version'):
            all_content.append(f"Genus Synthesis Solution {netlist_info['version']}")
        if netlist_info.get('full_timestamp'):
            all_content.append(f"Generated on: {netlist_info['full_timestamp']}")
        
        # Add SPEF version info
        if spef_info.get('program'):
            all_content.append(f"Program: {spef_info['program']}")
        if spef_info.get('version'):
            all_content.append(f"VERSION {spef_info['version']}")
        if spef_info.get('date'):
            all_content.append(f"DATE {spef_info['date']}")
        
        # Match patterns against content
        matched_patterns = set()
        for pattern in pattern_items:
            found = False
            matched_content = None
            for content in all_content:
                if self._match_pattern(content, [pattern]):
                    found = True
                    matched_content = content
                    break
            
            if found:
                matched_patterns.add(pattern)
                # Build found_items with file/version metadata
                if netlist_info.get('path') and ('Genus' in pattern or 'Generated on' in pattern):
                    metadata = self._metadata.get('netlist_success', {})
                    found_items[pattern] = {
                        'line_number': metadata.get('line_number', 0),
                        'file_path': metadata.get('file_path', ''),
                        'matched': matched_content
                    }
                elif spef_info.get('path') and ('Quantus' in pattern or 'DATE' in pattern or 'VERSION' in pattern):
                    metadata = self._metadata.get('spef_step_end', {})
                    found_items[pattern] = {
                        'line_number': metadata.get('line_number', 0),
                        'file_path': metadata.get('file_path', ''),
                        'matched': matched_content
                    }
                else:
                    found_items[pattern] = {
                        'line_number': 0,
                        'file_path': '',
                        'matched': matched_content
                    }
        
        # Find unmatched patterns
        for p in pattern_items:
            if p not in matched_patterns:
                missing_items[p] = {
                    'reason': 'Required pattern not found'
                }
        
        # Check SPEF skip status - add as extra_item if skipped
        if spef_info.get('status') == 'Skipped':
            metadata = self._metadata.get('spef_skipped', {})
            skip_reason = spef_info.get('skip_reason', 'SPEF reading was skipped')
            extra_items["SPEF Reading was skipped"] = {
                'line_number': metadata.get('line_number', 0),
                'file_path': metadata.get('file_path', ''),
                'reason': skip_reason
            }
        
        # Add other errors as extra items
        for error in errors:
            if not any(e in error for e in ["SPEF reading was skipped"]):
                extra_items[f"Error"] = {
                    'line_number': 0,
                    'file_path': '',
                    'reason': error
                }
        
        return found_items, missing_items, extra_items

    # =========================================================================
    # Golden Helper Methods (完整复用，禁止简化)
    # =========================================================================

    def _parse_sta_log(self) -> Dict[str, Any]:
        """
        Parse STA log file to extract netlist/SPEF information.
        
        Returns:
            Dict with keys:
            - netlist_path: Path to netlist file
            - netlist_status: Success/Failed
            - spef_path: Path to SPEF file (if any)
            - spef_status: Success/Failed/Skipped
            - errors: List of error messages
        """
        sta_info = {
            'netlist_path': None,
            'netlist_status': 'Not Found',
            'spef_path': None,
            'spef_status': 'Not Found',
            'errors': [],
            'warnings': []
        }
        
        # Validate input_files
        input_files_list, errors = self.validate_input_files()
        if errors:
            sta_info['errors'].extend(errors)
            return sta_info
        
        for file_path in input_files_list:
            if not file_path.exists():
                sta_info['errors'].append(f"STA log file not found: {file_path}")
                continue
            
            sta_log_dir = file_path.parent
            
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                lines = f.readlines()
            
            for line_num, line in enumerate(lines, 1):
                # Extract netlist file path: "Read Netlist: /path/to/file.v.gz"
                if 'Read Netlist:' in line:
                    match = re.search(r'Read Netlist:\s*(.+)', line)
                    if match:
                        netlist_path_str = match.group(1).strip()
                        netlist_abs_path = self._resolve_relative_path(netlist_path_str, sta_log_dir)
                        if netlist_abs_path:
                            sta_info['netlist_path'] = netlist_abs_path
                        else:
                            sta_info['netlist_relative_path'] = netlist_path_str
                        
                        self._metadata['netlist_cmd'] = {
                            'line_number': line_num,
                            'file_path': str(file_path)
                        }
                
                # Alternative netlist detection: "Reading verilog netlist '/path/to/file.v.gz'"
                elif 'Reading verilog netlist' in line:
                    match = re.search(r"Reading verilog netlist\s+'([^']+)'", line)
                    if match:
                        netlist_rel_path = match.group(1)
                        if not sta_info.get('netlist_path'):
                            netlist_abs_path = self._resolve_relative_path(netlist_rel_path, sta_log_dir)
                            if netlist_abs_path:
                                sta_info['netlist_path'] = netlist_abs_path
                            else:
                                sta_info['netlist_relative_path'] = netlist_rel_path
                    
                    self._metadata['netlist_reading'] = {
                        'line_number': line_num,
                        'file_path': str(file_path)
                    }
                
                # Netlist success indicator: "*** Netlist is unique"
                elif '*** Netlist is unique' in line or 'Netlist is unique' in line:
                    sta_info['netlist_status'] = 'Success'
                    self._metadata['netlist_success'] = {
                        'line_number': line_num,
                        'file_path': str(file_path)
                    }
                
                # Check netlist status: "Status: Success"
                elif 'Status:' in line and sta_info.get('netlist_path'):
                    match = re.search(r'Status:\s*(Success|Failed)', line)
                    if match:
                        status = match.group(1)
                        if sta_info['netlist_status'] == 'Not Found' or 'netlist' in lines[max(0, line_num-5):line_num][-1].lower():
                            sta_info['netlist_status'] = status
                            if status == 'Success':
                                self._metadata['netlist_success'] = {
                                    'line_number': line_num,
                                    'file_path': str(file_path)
                                }
                
                # SPEF skip detection: "[INFO] Skipping SPEF reading"
                elif 'Skipping SPEF reading' in line:
                    sta_info['spef_status'] = 'Skipped'
                    sta_info['errors'].append("SPEF reading was skipped")
                    self._metadata['spef_skipped'] = {
                        'line_number': line_num,
                        'file_path': str(file_path),
                        'reason': line.strip()
                    }
                
                # Track SPEF reading flow step
                elif 'Begin flow_step read_parasitics' in line:
                    self._metadata['spef_step_begin'] = {
                        'line_number': line_num,
                        'file_path': str(file_path)
                    }
                
                elif 'End flow_step read_parasitics' in line:
                    self._metadata['spef_step_end'] = {
                        'line_number': line_num,
                        'file_path': str(file_path)
                    }
                    if sta_info['spef_status'] != 'Skipped':
                        sta_info['spef_status'] = 'Success'
                
                # Extract SPEF file path: "Read SPEF: /path/to/file.spef.gz"
                elif 'Read SPEF:' in line:
                    match = re.search(r'Read SPEF:\s*(.+)', line)
                    if match:
                        spef_path_str = match.group(1).strip()
                        spef_abs_path = self._resolve_relative_path(spef_path_str, sta_log_dir)
                        if spef_abs_path:
                            sta_info['spef_path'] = spef_abs_path
                        
                        self._metadata['spef_cmd'] = {
                            'line_number': line_num,
                            'file_path': str(file_path)
                        }
                
                # Check SPEF status
                elif 'Status:' in line and sta_info.get('spef_path'):
                    match = re.search(r'Status:\s*(Success|Failed)', line)
                    if match:
                        status = match.group(1)
                        if sta_info['spef_status'] == 'Not Found' or 'spef' in lines[max(0, line_num-5):line_num][-1].lower():
                            sta_info['spef_status'] = status
                            if status == 'Success':
                                self._metadata['spef_step_end'] = {
                                    'line_number': line_num,
                                    'file_path': str(file_path)
                                }
        
        return sta_info


    def _parse_netlist_version(self, netlist_path: Path) -> Dict[str, str]:
        """
        Parse netlist file to extract version information.
        
        Expected format:
        // Generated by Cadence Genus(TM) Synthesis Solution 23.15-s099_1
        // Generated on: Nov 18 2025 15:58:15 IST (Nov 18 2025 10:28:15 UTC)
        
        Returns:
            Dict with keys: tool, version, date, time, full_timestamp
        """
        version_info = {
            'tool': '',
            'version': '',
            'date': '',
            'time': '',
            'full_timestamp': ''
        }
        
        if not netlist_path.exists():
            return version_info
        
        lines = self._read_file_content(netlist_path, max_lines=50)
        
        for line in lines:
            # Extract tool and version
            if 'Generated by' in line and 'Genus' in line:
                match = re.search(r'Synthesis Solution\s+([\d\.\-\w]+)', line)
                if match:
                    version_info['tool'] = 'Cadence Genus Synthesis Solution'
                    version_info['version'] = match.group(1)
            
            # Extract generation date
            elif 'Generated on:' in line:
                match = re.search(r'Generated on:\s+(\w+\s+\d+\s+\d+)\s+([\d:]+)', line)
                if match:
                    version_info['date'] = match.group(1)
                    version_info['time'] = match.group(2)
                    version_info['full_timestamp'] = f"{match.group(1)} {match.group(2)}"
        
        return version_info


    def _parse_spef_version(self, spef_path: Path) -> Dict[str, str]:
        """
        Parse SPEF file to extract version information.
        
        Expected format:
        *SPEF "IEEE 1481-1999"
        *DATE "Tue Jun 10 14:16:48 2025"
        *PROGRAM "Cadence Quantus Extraction"
        *VERSION "23.1.0-p075 Tue Sep 26 09:27:40 PDT 2023"
        
        Returns:
            Dict with keys: design, date, vendor, program, version, spef_standard
        """
        version_info = {
            'design': '',
            'date': '',
            'vendor': '',
            'program': '',
            'version': '',
            'spef_standard': ''
        }
        
        if not spef_path.exists():
            return version_info
        
        lines = self._read_file_content(spef_path, max_lines=100)
        
        for line in lines:
            if line.startswith('*SPEF'):
                match = re.search(r'\*SPEF\s+"([^"]+)"', line)
                if match:
                    version_info['spef_standard'] = match.group(1)
            elif line.startswith('*DESIGN'):
                match = re.search(r'\*DESIGN\s+"([^"]+)"', line)
                if match:
                    version_info['design'] = match.group(1)
            elif line.startswith('*DATE'):
                match = re.search(r'\*DATE\s+"([^"]+)"', line)
                if match:
                    version_info['date'] = match.group(1)
            elif line.startswith('*VENDOR'):
                match = re.search(r'\*VENDOR\s+"([^"]+)"', line)
                if match:
                    version_info['vendor'] = match.group(1)
            elif line.startswith('*PROGRAM'):
                match = re.search(r'\*PROGRAM\s+"([^"]+)"', line)
                if match:
                    version_info['program'] = match.group(1)
            elif line.startswith('*VERSION'):
                match = re.search(r'\*VERSION\s+"([^"]+)"', line)
                if match:
                    version_info['version'] = match.group(1)
        
        return version_info


    def _read_file_content(self, file_path: Path, max_lines: int = 100) -> List[str]:
        """
        Read file content, supporting both plain text and gzip compressed files.
        
        Args:
            file_path: Path to the file
            max_lines: Maximum number of lines to read from start
            
        Returns:
            List of lines from the file
        """
        if not file_path.exists():
            return []
        
        try:
            # Check if file is gzipped
            if file_path.suffix == '.gz':
                try:
                    with gzip.open(file_path, 'rt', encoding='utf-8', errors='ignore') as f:
                        lines = []
                        for i, line in enumerate(f):
                            if i >= max_lines:
                                break
                            lines.append(line)
                        return lines
                except (gzip.BadGzipFile, OSError):
                    pass
            
            # Read as plain text file
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                lines = []
                for i, line in enumerate(f):
                    if i >= max_lines:
                        break
                    lines.append(line)
                return lines
        except Exception as e:
            print(f"Warning: Failed to read {file_path}: {e}")
            return []


    def _resolve_relative_path(self, relative_path: str, sta_log_dir: Path) -> Optional[Path]:
        """
        Resolve relative path from STA log to absolute path.
        
        Args:
            relative_path: Relative path from STA log
            sta_log_dir: Directory containing the STA log file
            
        Returns:
            Absolute path if exists, None otherwise
        """
        if not relative_path:
            return None
        
        try:
            clean_path = relative_path.strip().strip('"').strip("'")
            
            # Try absolute path first
            abs_path = Path(clean_path)
            if abs_path.is_absolute() and abs_path.exists():
                return abs_path
            
            # Resolve relative to STA log directory
            abs_path = (sta_log_dir / clean_path).resolve()
            if abs_path.exists():
                return abs_path
            
            # Try from project root
            if self.root:
                abs_path = (self.root / clean_path).resolve()
                if abs_path.exists():
                    return abs_path
        except Exception as e:
            print(f"Warning: Failed to resolve path {relative_path}: {e}")
        
        return None


    def _match_pattern(self, text: str, patterns: List[str]) -> Optional[str]:
        """
        Check if text matches any pattern.
        
        Args:
            text: Text to check
            patterns: List of patterns (supports wildcards)
            
        Returns:
            Matched pattern if found, None otherwise
        """
        for pattern in patterns:
            try:
                # Convert wildcard to regex
                regex_pattern = pattern
                if '*' in pattern and not pattern.startswith('^'):
                    regex_pattern = pattern.replace('*', '.*')
                
                if re.search(regex_pattern, text, re.IGNORECASE):
                    return pattern
            except re.error:
                # Regex error, try exact match
                if pattern.lower() in text.lower():
                    return pattern
        return None


# ============================================================================
# Entry Point (Template - Fixed, Golden-Aligned)
# ============================================================================

def init_checker() -> NetlistSpefVersionChecker:
    """Initialize and return the checker instance."""
    checker = NetlistSpefVersionChecker()
    checker.init_checker()
    return checker


if __name__ == '__main__':
    checker = init_checker()
    checker.execute_check()
    checker.write_output()
