# Generated by Developer Agent - Agent C
# Model: claude-sonnet-4-5
# ItemSpec: IMP-10-0-0-00
# Generated at: 2026-01-28T11:42:31.957858

def check_existence(items: List[Dict[str, Any]]) -> Dict[str, Any]:
    """
    Universal existence checker.
    
    Args:
        items: List of items from Atom A
        
    Returns:
        Dict with keys: is_match (bool), reason (str), evidence (list)
    """
    if items is None:
        items = []
    
    is_match = len(items) > 0
    
    return {
        'is_match': is_match,
        'reason': f"Found {len(items)} item(s)" if is_match else "No items found",
        'evidence': items
    }